In [1]:
import pandas as pd

In [3]:
props = pd.read_csv("http://www.firstpythonnotebook.org/_static/committees.csv")

In [7]:
props.head(7)

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
0,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,382,1374469,YES ON PROPOSITION 51 - CALIFORNIANS FOR QUALI...,SUPPORT
1,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,383,1220380,COMMUNITY COLLEGE FACILITY COALITION ISSUES CO...,SUPPORT
2,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,384,1282321,TORLAKSON'S INVEST IN CALIFORNIA A BALLOT MEAS...,SUPPORT
3,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,385,1382843,CALIFORNIA TAXPAYERS AND EDUCATORS OPPOSED TO ...,OPPOSE
4,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,386,1362973,YES ON PROPOSITION 52 - A COALITION OF CALIFOR...,SUPPORT
5,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,387,1381488,CALIFORNIANS FOR HOSPITAL ACCOUNTABILITY AND Q...,OPPOSE
6,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,388,1373047,"SERVICE EMPLOYEES INTERNATIONAL UNION, UNITED ...",OPPOSE

In [8]:
props.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
ocd_prop_id               102 non-null object
calaccess_prop_id         102 non-null int64
ccdc_prop_id              102 non-null int64
prop_name                 102 non-null object
ccdc_committee_id         102 non-null int64
calaccess_committee_id    102 non-null int64
committee_name            102 non-null object
committee_position        102 non-null object
dtypes: int64(4), object(4)
memory usage: 4.8+ KB

In [9]:
contribs = pd.read_csv("http://www.firstpythonnotebook.org/_static/contributions.csv")

In [11]:
contribs.head()

,calaccess_committee_id,committee_name,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,BERGMAN,GRETCHEN,SPRING VALLEY,CA,91978,A NEW PATH,EXECUTIVE DIRECTOR,False,84.0
1,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,KAHLE,MYRNA,SAN DIEGO,CA,92109,NATIONAL SCHOOL DISTRICT,TEACHER,False,35.0
2,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-15,MCDEVITT,LEO,ESCONDIDO,CA,92025,LIFE IONIZERS,SEO/CONTENT MANAGER,False,198.0
3,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-08-10,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,False,-50.0
4,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-26,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,True,50.0

In [12]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [15]:
props.prop_name.value_counts().reset_index()

                                                index  prop_name
0   PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE...         13
1   PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...         12
2   PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...         11
3   PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...          9
4   PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...          8
5   PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...          7
6   PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...          7
7   PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES ...          6
8   PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...          4
9   PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...          4
10  PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUT...          4
11  PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...          4
12  PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...          4
13  PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...          3
14  PROPOSITION 061- STATE PRESCRIPTION DRUG PURCH...          3
15  PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH ...          2
16  PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...          1

In [20]:
contribs.contributor_lastname.value_counts().reset_index()

                                                   index  contributor_lastname
0                                                 GARCIA                   294
1                                                  SMITH                   291
2                                               MARTINEZ                   275
3                                                  LOPEZ                   256
4                                              RODRIGUEZ                   249
5                                              HERNANDEZ                   242
6                                                JOHNSON                   241
7                                               GONZALEZ                   206
8                                                  BROWN                   203
9                                                 MILLER                   199
10                                              WILLIAMS                   198
11                                                 JONES                   178
12                                               RAMIREZ                   172
13                                                 PEREZ                   171
14                                               SANCHEZ                   145
15                                                 DAVIS                   137
16                                                   LEE                   134
17                                              ANDERSON                   119
18                                                THOMAS                   117
19                                                FLORES                   115
20                                                 MOORE                   108
21                                             GUTIERREZ                   108
22                                                  DIAZ                   108
23                                                 GOMEZ                   105
24                                                CHAVEZ                   104
25                                              THOMPSON                    95
26                                                 WHITE                    94
27                                                TORRES                    93
28                                                WILSON                    93
29                                                 LEWIS                    93
...                                                  ...                   ...
18065                                               LUPU                     1
18066                                          AMEZQUITE                     1
18067  BUILDING INDUSTRY ASSOCIATION OF SOUTHERN CALI...                     1
18068                                         SALAZAR II                     1
18069                                             TROYER                     1
18070         PACIFIC BUILDERS HARDWARE & LIGHTING, INC.                     1
18071                                              NEALY                     1
18072                            SUISUN ROOFING & SUPPLY                     1
18073                                           MOSBY JR                     1
18074                                               LISK                     1
18075                                              CHING                     1
18076                                             BRANCO                     1
18077                                               LISH                     1
18078                                              HONIS                     1
18079                                   LUPIAN HERNANDEZ                     1
18080                                        ALLOR-CROSS                     1
18081                                              WAUGH                     1
18082                                             SUTYAK                     1
18083                                          WATERFALL                     1
18084                                            QUINLEY                     1
18085                                             PICENO                     1
18086                                             SIVERS                     1
18087                                              MACAY                     1
18088                                            EUSTICE                     1
18089                                           MARTINUS                     1
18090        CFHS HOLDINGS, INC./MARINA DEL REY HOSPITAL                     1
18091                                            CAMPION                     1
18092                                              WAKEN                     1
18093                                           LEVINSON                     1
18094                                             GEFFEN                     1

[18095 rows x 2 columns]